### ISSUE TITLE
Mekanism Turbine and Fluiducts Server Crash

### ISSUE THREAD

**Issue by ghost** [vagaprime/MageTech-Gate#11]
Hi Vaga! The title says it all but here are the version numbers and a copy of the crash report.

Pack Version: 1.9
Thermos Version: Thermos-1.7.10-1614-server [Build 57](https://github.com/CyberdyneCC/Thermos/releases)

Crash Log: http://pastebin.com/zSrn1vpP

**Comment by vagaprime** [comment]
ok I will pass this along to Aidan over at Mek.

edit:there is a chance that this has been fixed with mek 9.1 which mtg 1.10 has been updated to, but that version has not been tested enough to push. 

**MUST CONSCRIPT MORE TESTERS!**

**Comment by vagaprime** [comment]
the problem has been fixed in mek 9.1

**Comment by vagaprime** [comment]
pushing an update for the pack to update mek. was going to wait till mtg 1.10 but the crash bug is getting worse.

**Comment by vagaprime** [comment]
Mek 9.1 got pushed in a hot fix version. ready for upload to the server.
