### ISSUE TITLE
SonarCore+Practical Logistics causing large CPU drain

### ISSUE THREAD

**Issue by ghost** [vagaprime/MageTech-Gate#12]
Hi Vaga!

I am not sure how helpful this is to give to you, but I would like to provide it for reference's sake. The server's CPU while running version 1.9.3 of MageTech Gate was using over 75% for just Practical Logistics. The warmroast profile is below but I am afraid that is all I have. Please let me know if you need anything else I can provide.

Image: http://imgur.com/a/6OdNe

**Comment by vagaprime** [comment]
I can look into configs and see what I can change, but I will be sure to forward this issue onto the dev of SC and PL.

**Comment by vagaprime** [comment]
sadly the 1.7.10 versions of these mods are not supported anymore. So either we deal with them eating the cpu or I pull them from the pack. I want this pack to be as server friendly as it can be so your input on the matter is welcome Auric.

**Comment by ghost** [comment]
I have not seen the issue arise in a while, players appear to have disassembled their setups. If it becomes an issue again, we can disable it server side, no need to remove it from the pack.

**Comment by vagaprime** [comment]
ok
