### ISSUE TITLE
Infusion alter reward  not appearing until you are into breaking things down quest.

### ISSUE THREAD

**Issue by operative2259** [vagaprime/MageTech-Gate#15]
I completed Infusion Altar but did not get the reward button.  I went on to Breaking things down and some time later went back and it showed unclaimed reward.  Maybe a timing issue,.

**Comment by vagaprime** [comment]
hmm will look into how the quests are tied together.

**Comment by vagaprime** [comment]
Most TC quests have been removed to restore the mystery of the mod.
