### ISSUE TITLE
Academycraft Chapter  the recipe for the normal ability developer is off

### ISSUE THREAD

**Issue by operative2259** [vagaprime/MageTech-Gate#17]
It appears to want the charged version of the portable developer instead of teh uncharged one shown in NEI.   Also the next quest to build the portable developer seems to want the charged one also and you cannot craft a charged portable developer.

**Comment by vagaprime** [comment]
-mumbles grumbles- time to change them to Fuzzy.

**Comment by vagaprime** [comment]
fixed
