### ISSUE TITLE
1.10 crafting 

### ISSUE THREAD

**Issue by operative2259** [vagaprime/MageTech-Gate#19]
TC tables (stencil , tool station, etc) only register if crafted using oak wood and planks.

**Comment by vagaprime** [comment]
still trying to figure out how to fix that. if its set to fuzzy all you do is craft one table and they all get completed

**Comment by vagaprime** [comment]
In-till I can figure out how to get HQM to understand what is a tool station, a part builder, and table we are stuck with the quest wanting the wood ones
