### ISSUE TITLE
Request for a server files download

### ISSUE THREAD

**Issue by ghost** [vagaprime/MageTech-Gate#2]
Hi vaga!

This would make our lives much easier (in particular Helk's) if there was some sort of server files download to use when updating a server running MageTech Gate. :)

**Comment by vagaprime** [comment]
working on it. trying to figure a way to set up server files one a PC that barely wants to run mc. Need to check with a guy who offered to do server files for me.

**Comment by vagaprime** [comment]
Taken care of.
