### ISSUE TITLE
All tile entities stop working after one or two actions

### ISSUE THREAD

**Issue by ghost** [vagaprime/MageTech-Gate#3]
Hi Vaga!

UPDATE:
This is true for all tile entities from any mod. I am actively trying to determine the cause.

We have found a rather odd bug. The vanilla furnace will only cook one or two items before freezing (progress bar stops and no items are consumed). A slab furnace cooks items only if you have placed it and not ever unloaded the chunk.

Pack Version: 1.8.1
Disabled Mods: Lanteacraft 2, Roguelike Dungeons, HQM (LC2 and HQM until update)

We are currently using Thermos, a replacement for KCauldron. Please let me know if you need any more information. This may be specific to our setup but I wanted to let you know incase anyone else has this issue. :)

**Comment by vagaprime** [comment]
the servers have been tested on a normal forge server with no problem. Rob was the one that tested over night while I was asleep.

edit Rob was running a default thermos server

**Comment by vagaprime** [comment]
What plug-ins are being used?

**Comment by ghost** [comment]
Well, it seems that the issue may have been resolved. The mod, Tickprofiler, and the KCauldron Replacement we use, Thermos, were both messing with entity and tile entity lists. By disabling Tickprofiler, which is how we monitor the tps and high ticking entities unfortunately, we were able to resolve this issue.
