### ISSUE TITLE
Many kinds of Aluminium Ore Generating

### ISSUE THREAD

**Issue by ghost** [vagaprime/MageTech-Gate#4]
Hi Vaga!

Players are reporting finding ores from multiple mods generating in the overworld. These mods include Galacticraft, Immersive Engineering, and Tinker's Construct. Not a super important issue but still something that may tidy up the world generation a little bit. :)

**Comment by vagaprime** [comment]
meant to be like that, but I will look into disabling one of them

**Comment by vagaprime** [comment]
Aluminium ore has been pruned. only Tcon Aluminium should be spawning ok. Change will be pushed in 1.10
