### ISSUE TITLE
Nitor recipe through Botania is not working.

### ISSUE THREAD

**Issue by operative2259** [vagaprime/MageTech-Gate#7]
Catalyst is correct and other recipes work but glowstone to Nitor does not work.  It wants to go to redstone instead

**Comment by vagaprime** [comment]
hmm. It should just require a normal mana poll but that go broken after the mana powder got introduced. I will have to look into the script and see if I can make heads or tails about whats going on.

**Comment by vagaprime** [comment]
Corrected in 1.10. now takes a glowstone block and returns 4 nitor, also requires 4 times the amount of mana.
